config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'console' do
    scope module: 'admin' do
      resources :sessions, only: %i(new destroy), as: :admin_sessions
      get '/auth/:provider/callback' => 'sessions#create'

      get '/' => 'dashboard#index'

      resources :teams do
        collection do
          post :import
        end
      end

      resources :people do
        collection do
          post :import
        end
      end

      resources :desks do
        collection do
          post :import
        end
      end

      resources :machines do
        collection do
          get :lookup
          get :prometheus_config
          post :import
        end
      end

      resources :password_tiers do
        resources :passwords, only: %i(index) do
          collection do
            post :generate
            post :print
            post :export_to_cms
            post :export_to_machines
          end
        end
      end

      resources :contests do
      end

      resources :remote_tasks, only: %i(index new create) do
        resources :remote_task_executions, as: :executions, path: 'executions', only: %i(index show)

        collection do
          post :create_for_machines
        end
      end

      resources :hailings, only: %i(index)

      get '/metrics' => 'metrics#show'
    end
  end

  constraints subdomain: 'leader' do
    scope module: 'leader' do
      get '/', to: redirect('/contestants')
      resources :contestants, only: %i(index edit update)
    end
  end

  constraints subdomain: 'service' do
    scope module: 'service' do
      get '/', to: redirect('/hailings')
      resources :hailings, only: %i(index create)
      resource :special_requirement_note, only: %i(edit update)
    end
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  resources :sessions, only: %i(new create destroy)
end

app/models/password_tier.rb
class PasswordTier < ApplicationRecord
  belongs_to :contest, required: false
  has_many :passwords, dependent: :destroy

  scope :active, ->(t = Time.now) { where('(not_before < ? OR not_before IS NULL) AND (? < not_after OR not_after IS NULL)', t, t) }

  def active?(t = Time.now)
    (not_before ? not_before < t : true) && (not_after ? t < not_after : true)
  end

  def generate!(people:, overwrite: false)
    people.map do |person|
      password = passwords.find_or_initialize_by(person: person)
      if !password.persisted? || overwrite
        password.plaintext_password = Password.random
        password.save!
      end
      password
    end
  end
end

app/controllers/admin/password_tiers_controller.rb
require 'csv'

class Admin::PasswordTiersController < Admin::ApplicationController
  before_action :set_password_tier, only: [:show, :edit, :update, :destroy]

  # GET /password_tiers
  # GET /password_tiers.json
  def index
    @password_tiers = PasswordTier.all.includes(:contest)
  end

  # GET /password_tiers/new
  def new
    @password_tier = PasswordTier.new
  end

  # GET /password_tiers/1/edit
  def edit
  end

  # POST /password_tiers
  # POST /password_tiers.json
  def create
    @password_tier = PasswordTier.new(password_tier_params)

    respond_to do |format|
      if @password_tier.save
        format.html { redirect_to @password_tier, notice: 'PasswordTier was successfully created.' }
        format.json { render :show, status: :created, location: @password_tier }
      else
        format.html { render :new }
        format.json { render json: @password_tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /password_tiers/1
  # PATCH/PUT /password_tiers/1.json
  def update
    respond_to do |format|
      if @password_tier.update(password_tier_params)
        format.html { redirect_to @password_tier, notice: 'PasswordTier was successfully updated.' }
        format.json { render :show, status: :ok, location: @password_tier }
      else
        format.html { render :edit }
        format.json { render json: @password_tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /password_tiers/1
  # DELETE /password_tiers/1.json
  def destroy
    @password_tier.destroy
    respond_to do |format|
      format.html { redirect_to password_tiers_url, notice: 'PasswordTier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_password_tier
      @password_tier = PasswordTier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def password_tier_params
      params.require(:password_tier).permit(:description, :not_before, :not_after, :contest_id)
    end
end

app/views/admin/password_tiers/_form.html.haml
= form_with(model: password_tier, local: true, class: 'form-horizontal') do |form|
  - if password_tier.errors.empty?
    .form-group#error_explanation
      %ul
        - password_tier.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :description, class: 'form-control'

  .form-group
    = form.label :not_before, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.datetime_local_field :not_before, class: 'form-control'
  .form-group
    = form.label :not_after, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.datetime_local_field :not_after, class: 'form-control'

  .form-group
    = form.label :contest_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :contest_id, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-offset-2
      = form.submit(class: 'btn btn-primary')

app/views/admin/password_tiers/edit.html.haml
= content_for(:content_header) { "Editing PasswordTier" }
= render 'form', password_tier: @password_tier

app/views/admin/password_tiers/import.html.haml
- content_for(:content_header) { "PasswordTier Import Result" }

- if @errors.empty?
  %p No errors reported
- else
  %ul
    - @errors.each do |password_tier|
      %li
        %p= password_tier.name
        %ul
          - password_tier.errors.full_messages.each do |message|
            %li= message

= link_to 'Back', password_tiers_path, class: 'btn btn-default'

app/views/admin/password_tiers/index.html.haml
- content_for(:content_header) { "PasswordTiers" }

= link_to 'New PasswordTier', new_password_tier_path, class: 'btn btn-primary'

%table.table.table-hover
  %thead
    %tr
      %th Description
      %th Contest
      %th Not Before
      %th Not After
      %th{colspan: 2}
  %tbody
    - @password_tiers.each do |password_tier|
      %tr
        %td= link_to password_tier.description, password_tier_passwords_path(password_tier)
        %td
          - if password_tier.contest
            = password_tier.contest.name
        %td= password_tier.not_before
        %td= password_tier.not_after
        %td= link_to 'Edit', edit_password_tier_path(password_tier)
        %td= link_to 'Destroy', password_tier, method: :delete, data: {confirm: 'Are you sure?'}

app/views/admin/password_tiers/new.html.haml
= content_for(:content_header) { "New PasswordTier" }
= render 'form', password_tier: @password_tier