config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'console' do
    scope module: 'admin' do
      resources :sessions, only: %i(new destroy), as: :admin_sessions
      get '/auth/:provider/callback' => 'sessions#create'

      get '/' => 'dashboard#index'

      resources :teams do
        collection do
          post :import
        end
      end

      resources :people do
        collection do
          post :import
        end
      end

      resources :desks do
        collection do
          post :import
        end
      end

      resources :machines do
        collection do
          get :lookup
          get :prometheus_config
          post :import
        end
      end

      resources :password_tiers do
        resources :passwords, only: %i(index) do
          collection do
            post :generate
            post :print
            post :export_to_cms
            post :export_to_machines
          end
        end
      end

      resources :contests do
      end

      resources :remote_tasks, only: %i(index new create) do
        resources :remote_task_executions, as: :executions, path: 'executions', only: %i(index show)

        collection do
          post :create_for_machines
        end
      end

      resources :hailings, only: %i(index)

      get '/metrics' => 'metrics#show'
    end
  end

  constraints subdomain: 'leader' do
    scope module: 'leader' do
      get '/', to: redirect('/contestants')
      resources :contestants, only: %i(index edit update)
    end
  end

  constraints subdomain: 'service' do
    scope module: 'service' do
      get '/', to: redirect('/hailings')
      resources :hailings, only: %i(index create)
      resource :special_requirement_note, only: %i(edit update)
    end
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  resources :sessions, only: %i(new create destroy)
end

app/models/desk.rb
class Desk < ApplicationRecord
  belongs_to :floor
  belongs_to :contestant, class_name: 'Person', required: false
  belongs_to :machine, required: false

  has_many :assignment_histories, class_name: 'DeskAssignmentHistory'

  around_save :create_assignment_history

  def create_assignment_history
    create_history = self.contestant_id_changed? || self.machine_id_changed?
    yield
    if create_history
      self.assignment_histories.create!(
        contestant_id: self.contestant_id,
        machine_id: self.machine_id,
      )
    end
  end

  def contestant=(value)
    floor = case value
    when String
      Person.where(login: value).first
    else
      value
    end
    association(:contestant).writer(floor)
  end

  def machine=(value)
    machine = case value
    when String
      Machine.find_or_create_by!(mac: value)
    else
      value
    end
    association(:machine).writer(machine)
  end

  def floor=(value)
    floor = case value
    when String
      Floor.find_or_create_by!(name: value)
    else
      value
    end
    association(:floor).writer(floor)
  end
end

app/controllers/admin/desks_controller.rb
require 'csv'

class Admin::DesksController < Admin::ApplicationController
  before_action :set_desk, only: [:show, :edit, :update, :destroy]

  # GET /desks
  # GET /desks.json
  def index
    @desks = Desk.all.includes(:floor).includes(:contestant).includes(:machine).order(name: :asc)
    @machine_probe = MachineProber.new.statuses
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks
  # POST /desks.json
  def create
    @desk = Desk.new(desk_params)

    respond_to do |format|
      if @desk.save
        format.html { redirect_to @desk, notice: 'Desk was successfully created.' }
        format.json { render :show, status: :created, location: @desk }
      else
        format.html { render :new }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desks/1
  # PATCH/PUT /desks/1.json
  def update
    respond_to do |format|
      if @desk.update(desk_params)
        format.html { redirect_to @desk, notice: 'Desk was successfully updated.' }
        format.json { render :show, status: :ok, location: @desk }
      else
        format.html { render :edit }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1
  # DELETE /desks/1.json
  def destroy
    @desk.destroy
    respond_to do |format|
      format.html { redirect_to desks_url, notice: 'Desk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /desks/import
  def import
    csv = CSV.new(params[:csv].to_io, headers: true)
    @errors = []
    csv.each do |row|
      desk = Desk.find_or_initialize_by(name: row.fetch('name'))
      %w(floor contestant machine switch_host switch_interface).each do |key|
        next unless row.key?(key.to_s)
        value = if row[key.to_s].present?
          row[key.to_s]
        else
          nil
        end
        desk.__send__(:"#{key}=", value)
      end
      unless desk.save
        @errors << desk
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desk_params
      params.require(:desk).permit(:slug, :name, :contestant)
    end
end

app/views/admin/desks/_form.html.haml
= form_with(model: desk, local: true, class: 'form-horizontal') do |form|
  - if desk.errors.empty?
    .form-group#error_explanation
      %ul
        - desk.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :name, class: 'form-control'

  .form-group
    = form.label :floor, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :floor, value: desk.floor ? desk.floor.name : nil, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-offset-2
      = form.submit(class: 'btn btn-primary')

app/views/admin/desks/edit.html.haml
= content_for(:content_header) { "Editing Desk" }
= render 'form', desk: @desk

app/views/admin/desks/import.html.haml
- content_for(:content_header) { "Desk Import Result" }

- if @errors.empty?
  %p No errors reported
- else
  %ul
    - @errors.each do |desk|
      %li
        %p= desk.name
        %ul
          - desk.errors.full_messages.each do |message|
            %li= message

= link_to 'Back', desks_path, class: 'btn btn-default'

app/views/admin/desks/index.html.haml
- content_for(:content_header) { "Desks" }

= link_to 'New Desk', new_desk_path, class: 'btn btn-primary'

%section
  = form_tag import_desks_path, class: 'form-inline', multipart: true do
    .form-group
      = file_field_tag 'csv'
    .form-group
      = submit_tag 'Import', class: 'btn btn-default'
  %p.small CSV with headers (name,[floor],[machine],[contestant],[switch_host],[switch_interface])

%table.table.table-hover
  %thead
    %tr
      %th Floor
      %th Name
      - if params[:switch]
        %th Switch
        %th Iface
      %th Machine
      %th Machine IP
      %th Status
      %th Contestant
      %th{colspan: 2}
  %tbody
    - @desks.each do |desk|
      %tr
        %td= desk.floor.name
        %td= desk.name
        - if params[:switch]
          %td= desk.switch_host
          %td= desk.switch_interface
        %td
          #{desk.machine&.mac}
        %td
          - if desk.machine&.ip_address
            = desk.machine.ip_address
        %td
          - if desk.machine&.ip_address
            - status = @machine_probe.statuses&.fetch(desk.machine.ip_address, nil)
            - last = status&.last_succeeded_at&.in_time_zone('Asia/Tokyo') || 'N/A'
            - if status&.up
              %span.label.label-success{data: {toggle: 'tooltip', placement: "top"}, title: "at #{last}"} UP
            - elsif status.nil?
              %span.label.label-warning N/A
            - else
              %span.label.label-danger{data: {toggle: 'tooltip', placement: "top"}, title: "Last UP was #{last}"} DOWN

        %td
          - if desk.contestant
            #{desk.contestant.login} (#{desk.contestant.display_name})
        %td= link_to 'Edit', edit_desk_path(desk)
        %td= link_to 'Destroy', desk, method: :delete, data: {confirm: 'Are you sure?'}

%script
  jQuery(function ($) { $('[data-toggle=tooltip]').tooltip() })

app/views/admin/desks/new.html.haml
= content_for(:content_header) { "New Desk" }
= render 'form', desk: @desk