config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'console' do
    scope module: 'admin' do
      resources :sessions, only: %i(new destroy), as: :admin_sessions
      get '/auth/:provider/callback' => 'sessions#create'

      get '/' => 'dashboard#index'

      resources :teams do
        collection do
          post :import
        end
      end

      resources :people do
        collection do
          post :import
        end
      end

      resources :desks do
        collection do
          post :import
        end
      end

      resources :machines do
        collection do
          get :lookup
          get :prometheus_config
          post :import
        end
      end

      resources :password_tiers do
        resources :passwords, only: %i(index) do
          collection do
            post :generate
            post :print
            post :export_to_cms
            post :export_to_machines
          end
        end
      end

      resources :contests do
      end

      resources :remote_tasks, only: %i(index new create) do
        resources :remote_task_executions, as: :executions, path: 'executions', only: %i(index show)

        collection do
          post :create_for_machines
        end
      end

      resources :hailings, only: %i(index)

      get '/metrics' => 'metrics#show'
    end
  end

  constraints subdomain: 'leader' do
    scope module: 'leader' do
      get '/', to: redirect('/contestants')
      resources :contestants, only: %i(index edit update)
    end
  end

  constraints subdomain: 'service' do
    scope module: 'service' do
      get '/', to: redirect('/hailings')
      resources :hailings, only: %i(index create)
      resource :special_requirement_note, only: %i(edit update)
    end
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  resources :sessions, only: %i(new create destroy)
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :team, required: false
  has_one :desk, dependent: :nullify, foreign_key: :contestant_id
  has_many :assignment_histories, class_name: 'DeskAssignmentHistory', dependent: :nullify, foreign_key: :contestant_id
  has_many :passwords, dependent: :destroy
  has_many :hailings, dependent: :nullify, foreign_key: :contestant_id

  enum role: %i(staff contestant leader)

  before_validation do
    self.name = "#{first_name} #{last_name}" if (self.name.blank? || self.first_name_changed? || self.last_name_changed?) && first_name && last_name
  end

  def first_and_last_name
    if first_name.present? && last_name.present?
      {first_name: first_name, last_name: last_name}
    elsif display_name.present?
      first_name, last_name = display_name.split(/\s+/, 2)
      last_name ||= '.'
      {first_name: first_name, last_name: last_name}
    else
      raise "Name invalid"
    end
  end

  def team=(value)
    team = case value
    when String
      Team.where(slug: value).first
    else
      value
    end
    association(:team).writer(team)
  end

  def display_name
    case
    when name
      name
    when first_name && last_name
      "#{first_name} #{last_name}"
    end
  end

  def password_attempt(value)
    self.passwords.in_use.find { |_| _.attempt(value) }
  end
end

app/controllers/admin/people_controller.rb
require 'csv'

class Admin::PeopleController < Admin::ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all.includes(:team).order(login: :asc)
    if params[:role].present?
      @people = @people.where(role: params[:role])
    end
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /people/import
  def import
    csv = CSV.new(params[:csv].to_io, headers: true)
    @errors = []
    csv.each do |row|
      person = Person.find_or_initialize_by(login: row.fetch('login'))
      %w(team role name first_name last_name).each do |key|
        person.__send__(:"#{key}=", row[key.to_s]) if row[key.to_s]
      end
      unless person.save
        @errors << person
      end
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :login, :avatar_url, :role, :first_name, :last_name, :special_requirement_note, :team)
    end
end

app/views/admin/people/_form.html.haml
= form_with(model: person, local: true, class: 'form-horizontal') do |form|
  - if person.errors.empty?
    .form-group#error_explanation
      %ul
        - person.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :login, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :login, class: 'form-control'
  .form-group
    = form.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :name, class: 'form-control', placeholder: 'Display Name'
  .form-group
    %label.col-sm-2.control-label Full Name
    .col-sm-5
      = form.text_field :first_name, class: 'form-control', placeholder: 'First'
    .col-sm-5
      = form.text_field :last_name, class: 'form-control', placeholder: 'Last'
  .form-group
    = form.label :team, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :team, value: person.team ? person.team.slug : nil, class: 'form-control', placeholder: 'Team Slug'

  .form-group
    = form.label :avatar_url, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :avatar_url, class: 'form-control'
  .form-group
    = form.label :role, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.select :role, options_for_select(person.class.roles.keys, person.role), class: 'form-control'

  .form-group
    = form.label :special_requirement_note, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_area :special_requirement_note, class: 'form-control'
      %p Important: This is present to the contestant. Write in English.
      

  .form-group
    .col-sm-10.col-sm-offset-2
      = form.submit(class: 'btn btn-primary')

app/views/admin/people/edit.html.haml
= content_for(:content_header) { "Editing Person" }
= render 'form', person: @person

app/views/admin/people/import.html.haml
- content_for(:content_header) { "People Import Result" }

- if @errors.empty?
  %p No errors reported
- else
  %ul
    - @errors.each do |person|
      %li
        %p= person.login || person.name
        %ul
          - person.errors.full_messages.each do |message|
            %li= message

= link_to 'Back', people_path, class: 'btn btn-default'

app/views/admin/people/index.html.haml
- content_for(:content_header) { "People" }

= link_to 'New Person', new_person_path, class: 'btn btn-primary'

%section
  = form_tag import_people_path, class: 'form-inline', multipart: true do
    .form-group
      = file_field_tag 'csv'
    .form-group
      = submit_tag 'Import', class: 'btn btn-default'
  %p.small CSV with headers (login,[team],[role],[name],[first_name],[last_name])

= form_tag people_path, method: 'GET', class: 'form-inline' do
  .form-group
    = select_tag :role, options_for_select(Person.roles.to_a, params[:role])
  .form-group
    = submit_tag 'Filter', class: 'btn btn-default'

%table.table.table-hover
  %thead
    %tr
      %th login
      %th name
      %th team
      %th role
      %th note?
      %th{colspan: 2}
  %tbody
    - @people.each do |person|
      %tr
        %td= person.login
        %td= person.display_name
        %td= person.team&.name
        %td= person.role
        %td
          - if person.special_requirement_note.present?
            Y
        %td= link_to 'Edit', edit_person_path(person)
        %td= link_to 'Destroy', person, method: :delete, data: {confirm: 'Are you sure?'}

app/views/admin/people/new.html.haml
= content_for(:content_header) { "New Person" }
= render 'form', person: @person