config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'console' do
    scope module: 'admin' do
      resources :sessions, only: %i(new destroy), as: :admin_sessions
      get '/auth/:provider/callback' => 'sessions#create'

      get '/' => 'dashboard#index'

      resources :teams do
        collection do
          post :import
        end
      end

      resources :people do
        collection do
          post :import
        end
      end

      resources :desks do
        collection do
          post :import
        end
      end

      resources :machines do
        collection do
          get :lookup
          get :prometheus_config
          post :import
        end
      end

      resources :password_tiers do
        resources :passwords, only: %i(index) do
          collection do
            post :generate
            post :print
            post :export_to_cms
            post :export_to_machines
          end
        end
      end

      resources :contests do
      end

      resources :remote_tasks, only: %i(index new create) do
        resources :remote_task_executions, as: :executions, path: 'executions', only: %i(index show)

        collection do
          post :create_for_machines
        end
      end

      resources :hailings, only: %i(index)

      get '/metrics' => 'metrics#show'
    end
  end

  constraints subdomain: 'leader' do
    scope module: 'leader' do
      get '/', to: redirect('/contestants')
      resources :contestants, only: %i(index edit update)
    end
  end

  constraints subdomain: 'service' do
    scope module: 'service' do
      get '/', to: redirect('/hailings')
      resources :hailings, only: %i(index create)
      resource :special_requirement_note, only: %i(edit update)
    end
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  resources :sessions, only: %i(new create destroy)
end

app/models/machine.rb
class Machine < ApplicationRecord
  has_one :desk, dependent: :nullify
  has_many :assignment_histories, class_name: 'DeskAssignmentHistory', dependent: :nullify

  validates :mac, presence: true

  def mac=(value)
    write_attribute(:mac, normalize_mac(value))
  end

  def normalize_mac(value)
    value.gsub(/:/, '').downcase.chars.each_slice(2).map(&:join).join(':')
  end
end

app/controllers/admin/machines_controller.rb
require 'csv'

class Admin::MachinesController < Admin::ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  skip_before_action :require_staff, only: %i(lookup prometheus_config)

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all.order(mac: :asc)
  end

  def lookup
    machine = Machine.where(ip_address: params[:ip]).first
    return render(status: :not_found, json: {}) unless machine
    contestant = machine&.desk&.contestant && {
      id: machine.desk.contestant.login,
      name: machine.desk.contestant.display_name,
      special_requirement_note: machine.desk.contestant.special_requirement_note.presence,
    }
    desk = machine&.desk && {
      id: machine.desk.name,
      zone: machine.desk.floor.name,
    }
    render(json: {
      machine: {mac: machine.mac, ip_address: machine.ip_address},
      contestant:  contestant,
      desk: desk,
    })
  end

  def prometheus_config
    configs = Machine.includes(desk: [:contestant, :floor]).all.map do |m|
      next unless m.desk && m.ip_address
      {
        targets: ["#{m.ip_address}:9100"],
        labels: {
          ioi_desk: m.desk ? "#{m.desk.floor.name}/#{m.desk.name}" : nil,
          ioi_contestant: m.desk.contestant ? m.desk.contestant.login : nil,
        },
      }
    end.compact
    render(json: [
      *configs,
    ])
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /machines/import
  def import
    csv = CSV.new(params[:csv].to_io, headers: true)
    @errors = []
    csv.each do |row|
      machine = Machine.find_or_initialize_by(mac: row.fetch('mac'))
      [].each do |key|
        next unless row.key?(key.to_s)
        value = if row[key.to_s].present?
          row[key.to_s]
        else
          nil
        end
        machine.__send__(:"#{key}=", value)
      end
      unless machine.save
        @errors << machine
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:mac)
    end
end

app/views/admin/machines/_form.html.haml
= form_with(model: machine, local: true, class: 'form-horizontal') do |form|
  - if machine.errors.empty?
    .form-group#error_explanation
      %ul
        - machine.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :mac, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :mac, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-offset-2
      = form.submit(class: 'btn btn-primary')

app/views/admin/machines/edit.html.haml
= content_for(:content_header) { "Editing Machine" }
= render 'form', machine: @machine

app/views/admin/machines/import.html.haml
- content_for(:content_header) { "Machine Import Result" }

- if @errors.empty?
  %p No errors reported
- else
  %ul
    - @errors.each do |machine|
      %li
        %p= machine.name
        %ul
          - machine.errors.full_messages.each do |message|
            %li= message

= link_to 'Back', machines_path, class: 'btn btn-default'

app/views/admin/machines/index.html.haml
- content_for(:content_header) { "Machines" }

= link_to 'New Machine', new_machine_path, class: 'btn btn-primary'

%section
  = form_tag import_machines_path, class: 'form-inline', multipart: true do
    .form-group
      = file_field_tag 'csv'
    .form-group
      = submit_tag 'Import', class: 'btn btn-default'
  %p.small CSV with headers (mac)

%table.table.table-hover
  %thead
    %tr
      %th MAC Address
      %th IP Address
      %th{colspan: 2}
  %tbody
    - @machines.each do |machine|
      %tr
        %td= machine.mac
        %td= machine.ip_address
        %td= link_to 'Edit', edit_machine_path(machine)
        %td= link_to 'Destroy', machine, method: :delete, data: {confirm: 'Are you sure?'}

app/views/admin/machines/new.html.haml
= content_for(:content_header) { "New Machine" }
= render 'form', machine: @machine